/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/castle/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Castle(props) {
  const { nodes, materials } = useGLTF("/models/castle/model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface22.geometry} material={nodes.polySurface22.material} scale={0.01} />
    </group>
  )
}

useGLTF.preload("/models/castle/model.glb")   
