/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/airplane/dragon.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Dragon(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/dragon/model.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="RootNode">
          <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name="Dragon" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} skeleton={nodes.mesh_0.skeleton} />
            <skinnedMesh name="mesh_0_1" geometry={nodes.mesh_0_1.geometry} material={nodes.mesh_0_1.material} skeleton={nodes.mesh_0_1.skeleton} />
            <skinnedMesh name="mesh_0_2" geometry={nodes.mesh_0_2.geometry} material={nodes.mesh_0_2.material} skeleton={nodes.mesh_0_2.skeleton} />
            <skinnedMesh name="mesh_0_3" geometry={nodes.mesh_0_3.geometry} material={nodes.mesh_0_3.material} skeleton={nodes.mesh_0_3.skeleton} />
            <skinnedMesh name="mesh_0_4" geometry={nodes.mesh_0_4.geometry} material={nodes.mesh_0_4.material} skeleton={nodes.mesh_0_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/dragon/model.glb')
