/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/forest/model.glb
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Forest(props) {
  const { nodes, materials } = useGLTF('./models/forest/model.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.forest_012.geometry} material={nodes.forest_012.material} />
        <mesh geometry={nodes.forest_023.geometry} material={nodes.forest_023.material} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/forest/model.glb')
